version: "3.8"

services:
  ml-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recmind_ml_service
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT:-us-west1-gcp}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME:-news-articles}
      - ML_SERVICE_HOST=0.0.0.0
      - ML_SERVICE_PORT=8000
      - LOG_LEVEL=info
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - recmind_network

networks:
  recmind_network:
    driver: bridge