version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: recmind-postgres
    environment:
      POSTGRES_USER: recuser
      POSTGRES_PASSWORD: recpass
      POSTGRES_DB: recmind
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: recmind-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
