version: "3.8"

services:
  redis:
    image: redis:7
    container_name: recmind_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: recmind_rabbitmq
    ports:
      - "5672:5672"    # Main RabbitMQ port
      - "15672:15672"  # Web UI
    environment:
      RABBITMQ_DEFAULT_USER:  
      RABBITMQ_DEFAULT_PASS: recpass

